GET http://localhost:8080/health

###
GET http://localhost:8080/users/7

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "id": 7,
    "first_name": "Anish",
    "last_name": "Giri",
    "email": "ag@chess.com"
}