GET http://localhost:8080/health

###
GET http://localhost:8080/users/3

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "first_name": "Ding",
    "last_name": "Liren",
    "email": "dl@chess.com"
}